version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g aws-cdk
  build:
    commands:
      - echo Build started on `date`
      - npm run build || echo "No build script defined, skipping"
      - cdk synth > group2-cicd-project.template.json
  post_build:
    commands:
      - echo "Deploying stack..."
      - cdk deploy --require-approval never

artifacts:
  files:
    - '**/*'
